package GUI;

import civitas.CasillaCalle;

/**
 *
 * @author marin
 */
public class PropiedadPanel extends javax.swing.JPanel {

    CasillaCalle tituloPropiedad;
    
    public PropiedadPanel() {
        initComponents();
    }

    public void setPropiedad(CasillaCalle titulo){
        this.tituloPropiedad = titulo;
        this.nombre_prop_txt.setText(titulo.getNombre());
        Integer ncasas = titulo.getNumCasas();
        this.n_casas_txt.setText(ncasas.toString());
        Integer nhoteles = titulo.getNumHoteles();
        this.n_hoteles_txt.setText(nhoteles.toString());
        
        repaint();
        revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre_prop = new javax.swing.JLabel();
        nombre_prop_txt = new javax.swing.JTextField();
        n_casas = new javax.swing.JLabel();
        n_casas_txt = new javax.swing.JTextField();
        n_hoteles = new javax.swing.JLabel();
        n_hoteles_txt = new javax.swing.JTextField();

        nombre_prop.setText("Nombre");
        add(nombre_prop);

        nombre_prop_txt.setEditable(false);
        nombre_prop_txt.setText("nombre_prop");
        nombre_prop_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_prop_txtActionPerformed(evt);
            }
        });
        add(nombre_prop_txt);

        n_casas.setText("Nº casas");
        add(n_casas);

        n_casas_txt.setEditable(false);
        n_casas_txt.setText("n_casas");
        n_casas_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_casas_txtActionPerformed(evt);
            }
        });
        add(n_casas_txt);

        n_hoteles.setText("Nº hoteles");
        add(n_hoteles);

        n_hoteles_txt.setEditable(false);
        n_hoteles_txt.setText("n_hoteles");
        n_hoteles_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_hoteles_txtActionPerformed(evt);
            }
        });
        add(n_hoteles_txt);
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_prop_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_prop_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_prop_txtActionPerformed

    private void n_casas_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_casas_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_casas_txtActionPerformed

    private void n_hoteles_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_hoteles_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_hoteles_txtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel n_casas;
    private javax.swing.JTextField n_casas_txt;
    private javax.swing.JLabel n_hoteles;
    private javax.swing.JTextField n_hoteles_txt;
    private javax.swing.JLabel nombre_prop;
    private javax.swing.JTextField nombre_prop_txt;
    // End of variables declaration//GEN-END:variables
}
